FROM golang:1.17-alpine

WORKDIR /app

COPY go.mod ./

COPY go.sum ./

COPY main.go ./

COPY entity ./entity

COPY repo ./repo

COPY service ./service

COPY transport ./transport

RUN go mod download

RUN apk update && apk add gcc libc-dev

RUN apk update && apk add gcc

RUN go build main.go

EXPOSE 8080

CMD ["./main"]
