version: '3.8'
services:
  db:
    image: grpc-todo/db:1.0
    build: 
      context: .
      dockerfile: Dockerfile.database
    ports:
      - '5432:5432'
    healthcheck:
      test: pg_isready -U postgres
    # volumes:
    #   - postgres:/var/lib/postgresql/data
  server-go:
    image: grpc-todo/server:1.0
    build: 
      context: .
      dockerfile: Dockerfile.server
    depends_on: 
      db:
        condition: service_healthy
    ports:
      - '8080:8080'
    # volumes:
    #   - .:/app
# volumes:
#   postgres: